
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      ‚ҐабЁп MSBuild 17.7.2+d6990bcfa ¤«п .NET Framework
      ‘Ў®аЄ  ­ з в  02.03.2024 19:58:05.
      
      Џа®ҐЄв "C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      PrepareForBuild:
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\".
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        ‘®§¤ ­ЁҐ "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
        ЋЎа йҐ­ЁҐ Є "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ” ©« "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
        ЋЎа йҐ­ЁҐ Є "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      ‘Ў®аЄ  Їа®ҐЄв  "C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      
      ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
          ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
          ЋиЁЎ®Є: 0
      
      Џа®и«® ўаҐ¬Ґ­Ё 00:00:02.80
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/Пользователь/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/3.28.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      ‚ҐабЁп MSBuild 17.7.2+d6990bcfa ¤«п .NET Framework
      ‘Ў®аЄ  ­ з в  02.03.2024 19:58:08.
      
      Џа®ҐЄв "C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      PrepareForBuild:
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\".
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        ‘®§¤ ­ЁҐ "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
        ЋЎа йҐ­ЁҐ Є "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ” ©« "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
        ЋЎа йҐ­ЁҐ Є "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      ‘Ў®аЄ  Їа®ҐЄв  "C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      
      ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
          ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
          ЋиЁЎ®Є: 0
      
      Џа®и«® ўаҐ¬Ґ­Ё 00:00:02.19
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/Пользователь/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/3.28.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:6 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/CMakeScratch/TryCompile-5zvzc9"
      binary: "C:/Users/\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/CMakeScratch/TryCompile-5zvzc9"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Пользователь/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/CMakeScratch/TryCompile-5zvzc9'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_16fdd.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        ‚ҐабЁп MSBuild 17.7.2+d6990bcfa ¤«п .NET Framework
        ‘Ў®аЄ  ­ з в  02.03.2024 19:58:11.
        
        Џа®ҐЄв "C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\CMakeScratch\\TryCompile-5zvzc9\\cmTC_16fdd.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        PrepareForBuild:
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_16fdd.dir\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\CMakeScratch\\TryCompile-5zvzc9\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_16fdd.dir\\Debug\\cmTC_16fdd.tlog\\".
        InitializeBuildStatus:
          ‘®§¤ ­ЁҐ "cmTC_16fdd.dir\\Debug\\cmTC_16fdd.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
          ЋЎа йҐ­ЁҐ Є "cmTC_16fdd.dir\\Debug\\cmTC_16fdd.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_16fdd.dir\\Debug\\\\" /Fd"cmTC_16fdd.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "E:\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          ЋЇвЁ¬Ё§ЁагойЁ© Є®¬ЇЁ«пв®а Microsoft (R) C/C++ ўҐабЁЁ 19.37.32824 ¤«п x64
          CMakeCCompilerABI.c
          (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation).  ‚бҐ Їа ў  § йЁйҐ­л.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_16fdd.dir\\Debug\\\\" /Fd"cmTC_16fdd.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "E:\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\CMakeScratch\\TryCompile-5zvzc9\\Debug\\cmTC_16fdd.exe" /INCREMENTAL /ILK:"cmTC_16fdd.dir\\Debug\\cmTC_16fdd.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Џ®«м§®ў вҐ«м/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/CMakeScratch/TryCompile-5zvzc9/Debug/cmTC_16fdd.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Џ®«м§®ў вҐ«м/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/CMakeScratch/TryCompile-5zvzc9/Debug/cmTC_16fdd.lib" /MACHINE:X64  /machine:x64 cmTC_16fdd.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_16fdd.vcxproj -> C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\CMakeScratch\\TryCompile-5zvzc9\\Debug\\cmTC_16fdd.exe
        FinalizeBuildStatus:
          ” ©« "cmTC_16fdd.dir\\Debug\\cmTC_16fdd.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
          ЋЎа йҐ­ЁҐ Є "cmTC_16fdd.dir\\Debug\\cmTC_16fdd.tlog\\cmTC_16fdd.lastbuildstate".
        ‘Ў®аЄ  Їа®ҐЄв  "C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\CMakeScratch\\TryCompile-5zvzc9\\cmTC_16fdd.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        
        ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
            ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
            ЋиЁЎ®Є: 0
        
        Џа®и«® ўаҐ¬Ґ­Ё 00:00:01.92
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:6 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/CMakeScratch/TryCompile-azadq0"
      binary: "C:/Users/\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/CMakeScratch/TryCompile-azadq0"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Пользователь/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/CMakeScratch/TryCompile-azadq0'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_758b9.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        ‚ҐабЁп MSBuild 17.7.2+d6990bcfa ¤«п .NET Framework
        ‘Ў®аЄ  ­ з в  02.03.2024 19:58:14.
        
        Џа®ҐЄв "C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\CMakeScratch\\TryCompile-azadq0\\cmTC_758b9.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        PrepareForBuild:
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_758b9.dir\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\CMakeScratch\\TryCompile-azadq0\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_758b9.dir\\Debug\\cmTC_758b9.tlog\\".
        InitializeBuildStatus:
          ‘®§¤ ­ЁҐ "cmTC_758b9.dir\\Debug\\cmTC_758b9.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
          ЋЎа йҐ­ЁҐ Є "cmTC_758b9.dir\\Debug\\cmTC_758b9.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_758b9.dir\\Debug\\\\" /Fd"cmTC_758b9.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "E:\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          ЋЇвЁ¬Ё§ЁагойЁ© Є®¬ЇЁ«пв®а Microsoft (R) C/C++ ўҐабЁЁ 19.37.32824 ¤«п x64
          CMakeCXXCompilerABI.cpp
          (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation).  ‚бҐ Їа ў  § йЁйҐ­л.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_758b9.dir\\Debug\\\\" /Fd"cmTC_758b9.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "E:\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\CMakeScratch\\TryCompile-azadq0\\Debug\\cmTC_758b9.exe" /INCREMENTAL /ILK:"cmTC_758b9.dir\\Debug\\cmTC_758b9.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Џ®«м§®ў вҐ«м/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/CMakeScratch/TryCompile-azadq0/Debug/cmTC_758b9.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Џ®«м§®ў вҐ«м/Desktop/LOL/Laba1v1/newRes2/CMakeFiles/CMakeScratch/TryCompile-azadq0/Debug/cmTC_758b9.lib" /MACHINE:X64  /machine:x64 cmTC_758b9.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_758b9.vcxproj -> C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\CMakeScratch\\TryCompile-azadq0\\Debug\\cmTC_758b9.exe
        FinalizeBuildStatus:
          ” ©« "cmTC_758b9.dir\\Debug\\cmTC_758b9.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
          ЋЎа йҐ­ЁҐ Є "cmTC_758b9.dir\\Debug\\cmTC_758b9.tlog\\cmTC_758b9.lastbuildstate".
        ‘Ў®аЄ  Їа®ҐЄв  "C:\\Users\\Џ®«м§®ў вҐ«м\\Desktop\\LOL\\Laba1v1\\newRes2\\CMakeFiles\\CMakeScratch\\TryCompile-azadq0\\cmTC_758b9.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        
        ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
            ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
            ЋиЁЎ®Є: 0
        
        Џа®и«® ўаҐ¬Ґ­Ё 00:00:02.27
        
      exitCode: 0
...
